services:
  - type: web
    name: backend
    env: docker
    contextPath: backend
    dockerfilePath: Dockerfile
    envVars:
      - key: GOOGLE_API_KEY
        value: YOUR_API_KEY
    plan: free
    autoDeploy: true

  - type: web
    name: frontend-auth
    env: docker
    contextPath: doc-rag-ui
    dockerfilePath: Dockerfile
    plan: free
    autoDeploy: true
