services:
  - type: web
    name: backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: GOOGLE_API_KEY
        value: YOUR_API_KEY
    plan: free
    autoDeploy: true

  - type: web
    name: frontend-auth
    env: docker
    dockerfilePath: ./doc-rag-ui/Dockerfile
    plan: free
    autoDeploy: true
