services:
  - type: web
    name: backend
    env: docker
    dockerfilePath: Dockerfile
    contextPath: ./backend
    envVars:
      - key: GOOGLE_API_KEY
        value: YOUR_API_KEY
    plan: free
    autoDeploy: true

  - type: web
    name: frontend-auth
    env: docker
    dockerfilePath: Dockerfile
    contextPath: ./doc-rag-ui
    plan: free
    autoDeploy: true
